name:                trajectory-framework
version:             0.0.1
github:              "xsoufiane/trajectory-framework"
license:             BSD3
author:              "Soufiane Maguerra"
maintainer:          "soufiane.maguerra@commercetools.com"
copyright:           "2021 Soufiane Maguerra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xsoufiane/trajectory-framework#readme>

dependencies:
- base >= 4.7 && < 5
- HList
- time-framework
- either
- refined
- singletons
- template-haskell
- QuickCheck
- smallcheck
- tasty
- tasty-smallcheck

library:
  source-dirs: src
  exposed-modules: []

tests:
  trajectory-framework-spec:
    main: Spec.hs
    source-dirs:
    - test/spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - time-framework
    - QuickCheck
    - quickcheck-classes
    - smallcheck
    - tasty
    - tasty-quickcheck
    - tasty-smallcheck
    - string-interpolate
